using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;

namespace UDModifiers
{
    public class Program
    {
        public static Lazy<UDModifierSettings> _settings = null!;
        public static UDModifierSettings Settings => _settings.Value;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                            nickname: "ModifierSettings",
                            path: "modifier_settings.json",
                            out _settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "UD_Modifiers.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            
        }
    }
}
